;
; BIND data file for local loopback interface
;
$TTL	604800
@	IN	SOA	server.net.id. root.server.net.id. (
			      2		; Serial
			 604800		; Refresh
			  86400		; Retry
			2419200		; Expire
			 604800 )	; Negative Cache TTL
;
@	IN	NS	server.net.id.
@	IN	A	192.168.10.1
www	IN	A	192.168.10.1
